version: '3.8'

services:
  server1:
    build: ./server
    ports:
      - "5001:5000"
    environment:
      - SERVER_ID=server1

  server2:
    build: ./server
    ports:
      - "5002:5000"
    environment:
      - SERVER_ID=server2

  server3:
    build: ./server
    ports:
      - "5003:5000"
    environment:
      - SERVER_ID=server3
